//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSFFireData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Documents = new HashSet<Document>();
            this.Fees = new HashSet<Fee>();
            this.JournalEntries = new HashSet<JournalEntry>();
        }
    
        public int id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string PlanCheckNumber { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> FinalSignOff { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string APN { get; set; }
        public string ProjectType { get; set; }
        public bool PlansReceived { get; set; }
        public bool OnHold { get; set; }
        public string HoldDescription { get; set; }
        public string Notes { get; set; }
        public bool Oct2007Related { get; set; }
        public bool SeeFileCabinet { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> LandscapeContactId { get; set; }
        public int PropertyOwnerId { get; set; }
        public Nullable<int> ConstructionType { get; set; }
        public bool Basement { get; set; }
        public Nullable<int> SprinklerContractorId { get; set; }
        public Nullable<int> OriginalSqFt { get; set; }
        public Nullable<int> Stories { get; set; }
        public Nullable<int> SqFtAdded { get; set; }
        public string FireFlow { get; set; }
        public Nullable<int> UFCYear { get; set; }
        public int ParcelId { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<JournalEntry> JournalEntries { get; set; }
        public virtual Parcel Parcel { get; set; }
        public virtual Person Person { get; set; }
    }
}
