//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSFFireData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public string AddressNumber { get; set; }
        public string Street1 { get; set; }
        public string APN { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string PlanCheckNumber { get; set; }
        public string Notes { get; set; }
    }
}
