//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSFFireData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.Parcels = new HashSet<Parcel>();
            this.Projects = new HashSet<Project>();
        }
    
        public int id { get; set; }
        public string Street1 { get; set; }
    
        public virtual ICollection<Parcel> Parcels { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
